// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuYLgSIaA1fgmaEuI7ypYswhg3YiV7MGI',
    appId: '1:470906921112:web:57363193e4130d0abfb0ed',
    messagingSenderId: '470906921112',
    projectId: 'my-first-parkingps',
    authDomain: 'my-first-parkingps.firebaseapp.com',
    storageBucket: 'my-first-parkingps.appspot.com',
    measurementId: 'G-DZ1XFP3KG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqpjXQ5p8rcaf770cF81ZTE9pyMdlAcVo',
    appId: '1:470906921112:android:ce977d567d2bd412bfb0ed',
    messagingSenderId: '470906921112',
    projectId: 'my-first-parkingps',
    storageBucket: 'my-first-parkingps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ekTyWlone43z5fsZvgOqNnc5r-D7XJY',
    appId: '1:470906921112:ios:62f5d147a0fa2657bfb0ed',
    messagingSenderId: '470906921112',
    projectId: 'my-first-parkingps',
    storageBucket: 'my-first-parkingps.appspot.com',
    iosClientId: '470906921112-28397md9lpr09lkp5vp0drrgu6anfl9m.apps.googleusercontent.com',
    iosBundleId: 'sb.prk.parkingps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ekTyWlone43z5fsZvgOqNnc5r-D7XJY',
    appId: '1:470906921112:ios:0a89402455eda370bfb0ed',
    messagingSenderId: '470906921112',
    projectId: 'my-first-parkingps',
    storageBucket: 'my-first-parkingps.appspot.com',
    iosClientId: '470906921112-2pojnec6iahg27ps6qpqc0kh7rt3aocj.apps.googleusercontent.com',
    iosBundleId: 'sb.prk.parkingps.RunnerTests',
  );
}
